### ISSUE TITLE
replace mapstore with tm-db

### ISSUE THREAD

**Issue by marbar3778** [lazyledger/smt#6]
# Proposal: 

Replace the mapstore with tm-db. tm-db supports 5 different key value stores. This change is trivial and I can pick it up if its accepted.

[tm-db](https://github.com/tendermint/tm-db)

**Comment by musalbas** [comment]
Would this be simply a matter of replacing MapStore with this DB interface? https://github.com/tendermint/tm-db/blob/v0.6.1/types.go#L21

**Comment by marbar3778** [comment]
> Would this be simply a matter of replacing MapStore with this DB interface? [https://github.com/tendermint/tm-db/blob/v0.6.1/types.go#L21](https://github.com/tendermint/tm-db/blob/v0.6.1/types.go?rgh-link-date=2020-08-24T09%3A40%3A10Z#L21)

yes

**Comment by musalbas** [comment]
Sounds good to me. I assume there is an in-memory/dummy key value-store that can be used for tests?

**Comment by marbar3778** [comment]
> Sounds good to me. I assume there is an in-memory/dummy key value-store that can be used for tests?

yes it uses https://github.com/google/btree under the hood

**Comment by musalbas** [comment]
What about simply renaming Put to Set, and Del to Delete in the [MapStore interface](https://github.com/lazyledger/smt/blob/master/mapstore.go#L8)? This should make the MapStore interface a subset of the DB interface, and so you should be able to plug a DB instead of a MapStore?

**Comment by marbar3778** [comment]
> What about simply renaming Put to Set, and Del to Delete in the [MapStore interface](https://github.com/lazyledger/smt/blob/master/mapstore.go?rgh-link-date=2020-08-24T09%3A59%3A30Z#L8)? This should make the MapStore interface a subset of the DB interface, and so you should be able to plug a DB instead of a MapStore?

that is an option. I can look at making this change later today.

**Comment by musalbas** [comment]
Ok, sounds good
